routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['namespace' => 'Admin', 'middleware' => 'can:adm'], function () {
    Route::resource('/usuarios', 'UsersController')->except(['create','show']);
    Route::resource('/roles', 'RolesController')->except(['create','show']);
});


Route::group(['namespace' => 'Portal',  'middleware' => 'auth'], function () {
	
	//PORTAL
	Route::redirect('/', '/home', 301);
	Route::get('/home', 'PortalController@index')->name('home');
	

	//OGS
	Route::get('ogs/closed', 'OgsController@showClosedOgs');
	
	//PFS
	Route::get('pfs/list', 'PfsController@showClosedPfs');
	

	//SEARCH
	Route::post('ogs/closed/find', 'SearchController@searchOg');
	Route::post('/pfs/list/find', 'SearchController@searchPf');
	Route::post('/links/find', 'SearchController@searchLink');
	
	
	
	//EVENTS
	Route::get('events', 'EventController@index')->name('events.index');
	Route::post('events', 'EventController@addEvent')->name('events.add');
	
	//FAC
	Route::resource('/faq', 'FaqController')->except(['show','edit','update']);
	
	//FORUM
	Route::resource('/forum', 'ForumController')->except(['show','edit','update']);
	

	//ROTAS COMPLETAS PARA OS CONTROLLERS
	Route::resources([
		'ogs' => 'OgsController',
		'pfs' => 'PfsController',
		'tel' => 'TelController',
		'links' => 'UsefulLinksController'
	]);


});

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Role extends Model
{
    protected $fillable = [
        'name', 'label'
    ];

    public function setNameAttribute($value) {
        $this->attributes['name'] = strtolower($value);
    }

    public function permissions() {

        return $this->belongsToMany(\App\Permission::class);
    }

    public function getCreatedAtAttribute($value) {

        return Carbon::parse($value)->format('d/m/Y');
    }
}

resources/views/admin/editarRole.blade.php
@if($roles)

<form role="form" method="POST" action="{{route('roles.update',$roles->id)}}">
    @csrf
    @method('PUT')
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span></button>
        <h4 class="modal-title">Editar Perfil</h4>
    </div>
    <div class="modal-body">
        <div class="box-body">
            <div class="form-group">
                <label>Nome</label>
                <input name="name" type="text" class="form-control" placeholder="Nome" value="{{$roles->name}}" autocomplete="off">
            </div>
            <div class="form-group">
                <label>Descrição</label>
                <input name="label" type="text" class="form-control" placeholder="Descrição" value="{{$roles->label}}" autocomplete="off">
            </div>
            <div class="form-group">
                <label>Permissões</label>
                <select {{$roles->name=='adm'?'disabled':''}} name="permission[]" class="form-control select2" multiple="multiple"  style="width: 100%;">
                    @foreach ($permissions as $permission) 
                    @if(in_array($permission->name,$permissao))
                    <option title="{{$permission->label}}" value="{{$permission->id}}" selected>{{$permission->name}}</option>
                    @else
                    <option title="{{$permission->label}}" value="{{$permission->id}}">{{$permission->name}}</option>
                    @endif
                    @endforeach
                </select>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" onclick="event.preventDefault(); document.getElementById('delete-role').submit();" class="btn btn-danger pull-left" {{$roles->name=='adm'?'disabled':''}} ><i class="fa fa-trash"></i> Apagar Nível</button>
        <button type="submit" class="btn btn-primary" {{$roles->name=='adm'?'disabled':''}}><i class="fa fa-save"></i> Salvar</button>
        <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-times"></i> Fechar</button>
    </div>
</form>
<form id="delete-role" action="{{ route('roles.destroy', $roles->id) }}" method="POST" style="display: none;">
    @method('DELETE')
    @csrf
</form>
<script>
    $(function () {

        $('select').select2({
            width: '100%',
            language: "pt-BR"
        });
    });
</script>
@endif

resources/views/admin/editarUsuario.blade.php
@if($user)
<form role="form" method="POST" action="{{route('usuarios.update',$user->id)}}">
    @csrf
    @method('PUT')
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span></button>
        <h4 class="modal-title">Editar Usuário</h4>
    </div>
    <div class="modal-body">
        <div class="box-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label>Nome</label>
                        <input name="name" type="text" class="form-control" placeholder="Nome Completo" value="{{$user->name}}" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <label>Usuário</label>
                        <input name="username" type="text" class="form-control" placeholder="Usuário" value="{{$user->username}}" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <label>Email</label>
                        <input name="email" type="text" class="form-control" placeholder="Email Corporativo" value="{{$user->email}}" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <label>Perfil</label>
                        <select class="form-control" name="role">
                            @foreach ($roles as $role)
                            @foreach ($user->roles as $value)
                            <option value="{{$role->id}}" {{$value->label==$role->label?'selected':''}}>{{$role->label}}</option>
                            @endforeach
                            @endforeach
                        </select>
                    </div>
                </div>
            </div> 
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" onclick="event.preventDefault(); document.getElementById('delete-user').submit();" class="btn btn-danger pull-left"><i class="fa fa-trash"></i> Apagar Usuário</button>
        <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Salvar</button>
        <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-times"></i> Fechar</button>
    </div>
</form>
<form id="delete-user" action="{{ route('usuarios.destroy', $user->id) }}" method="POST" style="display: none;">
    @method('DELETE')
    @csrf
</form>
<script>
    $(function () {
        $('select').select2({
            width: '100%',
            language: "pt-BR"
        });
    });
</script>
@endif

resources/views/admin/roles.blade.php
@extends('adminlte::page')

@section('title', 'Portal Corporativo - Cadastro Perfil')


@section('content_header')
<h1>Nível de acesso</h1>
<ol class="breadcrumb">
    <li><a href="{{route('home')}}"><i class="fa fa-home"></i> Home</a></li>
    <li class="active">Nível de acesso</li>
</ol>
@stop

@section('content')
<div class="row">
    <div class="col-lg-12">
            @include('includes.alerts')
        <div class="box box-primary">
            <div class="box-header">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-new"><i class="fa fa-plus"></i> Cadastrar</button>
            </div>
            <div class="box-body">
                <table id="table" class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Descrição</th>
                            <th>Criado</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($roles as $role)
                        <tr id="{{$role->id}}">
                            <td>{{$role->name}}</td>
                            <td>{{$role->label}}</td>
                            <td>{{$role->created_at}}</td>
                        </tr>
                        @empty
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modal-new" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <form role="form" method="post" action="">
                {!! csrf_field() !!}
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span></button>
                    <h4 class="modal-title">Cadastrar Perfil</h4>
                </div>
                <div class="modal-body">

                    <div class="box-body">
                        <div class="form-group">
                            <label>Nome</label>
                            <input name="name" type="text" class="form-control" placeholder="Nome" value="{{old('name')}}" autocomplete="off">
                        </div>
                        <div class="form-group">
                            <label>Descrição</label>
                            <input name="label" type="text" class="form-control" placeholder="Descrição" value="{{old('label')}}" autocomplete="off">
                        </div>
                        <div class="form-group">
                            <label>Permissões</label>
                            <select name="permission[]" class="form-control select2" multiple="multiple"  style="width: 100%;">
                                @foreach ($permissions as $permission)
                                <option title="{{$permission->label}}" value="{{$permission->id}}">{{$permission->name}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Salvar</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-times"></i> Fechar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="modal fade" id="modal-edit" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content" id="conteudoModal">

        </div>
    </div>
</div>

@stop
@push('js')
<script src="{{ asset('vendor/adminlte/dist/js/roles.js') }}"></script>
@endpush

resources/views/admin/usuarios.blade.php
@extends('adminlte::page')

@section('title', 'Portal Corporativo - Usuários')

@section('content_header')
<h1>Usuários</h1>
<ol class="breadcrumb">
    <li><a href="{{route('home')}}"><i class="fa fa-home"></i> Home</a></li>
    <li class="active">Usuários</li>
</ol>
@stop

@section('content')
<div class="row">
    <div class="col-lg-12">
            @include('includes.alerts')
        <div class="box box-primary">
            <div class="box-header">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-new"><i class="fa fa-plus"></i> Cadastrar</button>
            </div>
            <div class="box-body">
                <table id="table_user" class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Usuário</th>
                            <th>Email</th>
                            <th>Nivel</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($usuarios as $user)
                        <tr id="{{$user->id}}">
                            <td>{{$user->name}}</td>
                            <td>{{$user->username}}</td>
                            <td>{{$user->email}}</td>
                            <td>
                                @foreach ($user->roles as $role)
                                {{$role->label}}
                                @endforeach
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modal-new" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <form role="form" method="post" action="" enctype="multipart/form-data">
                {!! csrf_field() !!}
                <input name="password" type="hidden" class="form-control" value="mudar123">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span></button>
                    <h4 class="modal-title">Cadastrar Usuário</h4>
                </div>
                <div class="modal-body">

                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Nome</label>
                                    <input name="name" type="text" class="form-control" placeholder="Nome Completo" value="{{old('name')}}" autocomplete="off">
                                </div>
                                <div class="form-group">
                                    <label>Usuário</label>
                                    <input name="username" type="text" class="form-control" placeholder="Usuário" value="{{old('username')}}" autocomplete="off">
                                </div>
                                <div class="form-group">
                                    <label>Email</label>
                                    <input name="email" type="text" class="form-control" placeholder="Email Corporativo" value="{{old('email')}}" autocomplete="off">
                                </div>
                                <div class="form-group">
                                    <label>Nivel</label>
                                    <select name="role" class="form-control">
                                        <option value="" disabled="" selected="">Selecione</option>
                                        @foreach ($roles as $role)
                                        <option {{ old('role') == $role->id ? "selected" : "" }} value="{{$role->id}}">{{$role->label}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <span class="pull-left">Senha padrão: <b>mudar123</b></span>
                    <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Salvar</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-times"></i> Fechar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="modal fade" id="modal-edit" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content" id="conteudoModal">

        </div>
    </div>
</div>

@stop
@push('js')
<script src="{{ asset('vendor/adminlte/dist/js/usuarios.js') }}"></script>
@endpush