routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['namespace' => 'Admin', 'middleware' => 'can:adm'], function () {
    Route::resource('/usuarios', 'UsersController')->except(['create','show']);
    Route::resource('/roles', 'RolesController')->except(['create','show']);
});


Route::group(['namespace' => 'Portal',  'middleware' => 'auth'], function () {
	
	//PORTAL
	Route::redirect('/', '/home', 301);
	Route::get('/home', 'PortalController@index')->name('home');
	

	//OGS
	Route::get('ogs/closed', 'OgsController@showClosedOgs');
	
	//PFS
	Route::get('pfs/list', 'PfsController@showClosedPfs');
	

	//SEARCH
	Route::post('ogs/closed/find', 'SearchController@searchOg');
	Route::post('/pfs/list/find', 'SearchController@searchPf');
	Route::post('/links/find', 'SearchController@searchLink');
	
	
	
	//EVENTS
	Route::get('events', 'EventController@index')->name('events.index');
	Route::post('events', 'EventController@addEvent')->name('events.add');
	
	//FAC
	Route::resource('/faq', 'FaqController')->except(['show','edit','update']);
	
	//FORUM
	Route::resource('/forum', 'ForumController')->except(['show','edit','update']);
	

	//ROTAS COMPLETAS PARA OS CONTROLLERS
	Route::resources([
		'ogs' => 'OgsController',
		'pfs' => 'PfsController',
		'tel' => 'TelController',
		'links' => 'UsefulLinksController'
	]);


});

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Role extends Model
{
    protected $fillable = [
        'name', 'label'
    ];

    public function setNameAttribute($value) {
        $this->attributes['name'] = strtolower($value);
    }

    public function permissions() {

        return $this->belongsToMany(\App\Permission::class);
    }

    public function getCreatedAtAttribute($value) {

        return Carbon::parse($value)->format('d/m/Y');
    }
}

app/Http/Controllers/Portal/EventController.php
<?php

namespace App\Http\Controllers\Portal;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use App\Http\Controllers\Controller;
use Auth;
use Validator;
use App\Models\Event;
use Calendar;

class EventController extends Controller
{
    public function index(){
			$events = Event::get();
			$event_list = [];
			foreach ($events as $key => $event) {
				$event_list[] = Calendar::event(
					$event->event_name,
					true,
					new \DateTime($event->start_date),
					new \DateTime($event->end_date.' +1 day')
				);
			}
			$calendar_details = Calendar::addEvents($event_list); 
 
			return view('portal.events', compact('calendar_details') );
	}
			
	public function addEvent(Request $request)
	{
		$validator = Validator::make($request->all(), [
				'event_name' => 'required',
				'start_date' => 'required',
				'end_date' => 'required',
		]);
		
        if ($validator->fails()) {
        	\Session::flash('warnning','Please enter the valid details');
            return Redirect::to('/events')->withInput()->withErrors($validator);
        }
		
		$event = new Event;
		
	
        $event = new Event;
        $event->event_name = $request['event_name'];
        $event->start_date = $request['start_date'];
        $event->end_date = $request['end_date'];
        $event->save();
			
		 \Session::flash('success','Event added successfully.');
        return Redirect::to('/events');
	}	
		

}

app/Http/Controllers/Portal/FaqController.php
<?php

namespace App\Http\Controllers\Portal;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Validator;
use App\Models\Faq;
use App\Models\FaqTag;
use App\Models\FaqResposta;

class FaqController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $faqs = faq::with('user')->paginate(10);

        return view('portal.faq', compact('faqs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $dados = $request->all();

        $validator = Validator::make($dados,[
            'resposta' => ['required','min:3'],
        ])->validate();

        $faq = Faq::find($request->faq_id);
        $faq->resposta()->delete();
        $faq->resposta()->create([
            'resposta' => $request->resposta
        ]);

        return redirect()->route('faq.index')->with('success', 'Resposta enviada com sucesso.');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $dados = $request->all();

        $validator = Validator::make($dados,[
            'pergunta' => ['required','min:3','max:255'],
            'tag' => ['required'],
        ])->validate();

        $dados['user_id'] = Auth()->user()->id;
        
        $insert = Faq::create($dados);
        
        $faq = Faq::find($insert->id);
        
        foreach($dados['tag'] as $tag){
            $faq->tag()->create([
                'tag' => $tag
            ]);
        }

        if ($insert) {
            return redirect()->route('faq.index')->with('success', 'Pergunta enviada com sucesso.');
        } else {
            return redirect()->route('faq.index')->with('error', 'Erro ao enviar a pergunta!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $faq = Faq::find($id);

        $delete = $faq->delete();

        if ($delete) {
            return redirect()->route('faq.index')->with('success', 'Pergunta apagada com sucesso.');
        } else {
            return redirect()->route('faq.index')->with('error', 'Erro ao apagar a pergunta!');
        }
    }

    public function responder(Request $request)
    {
        dd($request);
    }
}

app/Http/Controllers/Portal/ForumController.php
<?php

namespace App\Http\Controllers\Portal;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Validator;
use App\Models\Forum;
use App\Models\ForumTag;
use App\Models\ForumResposta;

class ForumController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $forums = forum::with('user')->paginate(10);

        return view('portal.forum', compact('forums'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $dados = $request->all();

        $validator = Validator::make($dados,[
            'resposta' => ['required','min:3'],
        ])->validate();

        $forum = forum::find($request->forum_id);
        $forum->resposta()->delete();
        $forum->resposta()->create([
            'resposta' => $request->resposta
        ]);

        return redirect()->route('forum.index')->with('success', 'Resposta enviada com sucesso.');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $dados = $request->all();

        $validator = Validator::make($dados,[
            'pergunta' => ['required','min:3','max:255'],
            'tag' => ['required'],
        ])->validate();

        $dados['user_id'] = Auth()->user()->id;
        
        $insert = forum::create($dados);
        
        $forum = forum::find($insert->id);
        
        foreach($dados['tag'] as $tag){
            $forum->tag()->create([
                'tag' => $tag
            ]);
        }

        if ($insert) {
            return redirect()->route('forum.index')->with('success', 'Pergunta enviada com sucesso.');
        } else {
            return redirect()->route('forum.index')->with('error', 'Erro ao enviar a pergunta!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $dados = $request->all();

        $validator = Validator::make($dados,[
            'resposta' => ['required','min:3'],
        ])->validate();

        $forum = forum::find($request->forum_id);
        $forum->resposta()->delete();
        $forum->resposta()->create([
            'resposta' => $request->resposta
        ]);

        return redirect()->route('forum.index')->with('success', 'Resposta enviada com sucesso.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $forum = forum::find($id);

        $delete = $forum->delete();

        if ($delete) {
            return redirect()->route('forum.index')->with('success', 'Pergunta apagada com sucesso.');
        } else {
            return redirect()->route('forum.index')->with('error', 'Erro ao apagar a pergunta!');
        }
    }

    public function responder(Request $request)
    {
        dd($request);
    }
}

app/Http/Controllers/Portal/OgsController.php
<?php

namespace App\Http\Controllers\Portal;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Og;



class OgsController extends Controller
{
	public function __construct()
    {
       $this->middleware('auth')->except('logout');
    }
    
	/**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {	
		//$this->store();
		return $this->showLiveJson();
		//return $this->showOpenOgs();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
		// cron every minute
	}

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store()
    {	
		$ogs = $this->getOgsFromUrl();
		foreach($ogs as $og) {		
			if(Og::where('protocolo',  $og['PROTOCOLO'])->first()['protocolo'] == $og['PROTOCOLO']){
				Og::where('protocolo',  $og['PROTOCOLO'])->update(['descricao' => $og['DESC_EQPTO']]);
				error_log("[UPDATE] - Observações do protocolo " . Og::where('protocolo',  $og['PROTOCOLO'])->first()['protocolo'] . " atualizadas.");
				continue;
			}else{
				$ogToSave = new Og;
				$ogToSave->protocolo = $og['PROTOCOLO'];
				$ogToSave->fila = $og['FILA'];
				$ogToSave->circuito = $og['CIRCUITO'];
				$ogToSave->status = $og['STATUS'];
				$ogToSave->entrada_fila = $og['ENTRADA_FILA'];
				$ogToSave->vencimento_anatel = $og['VENCIMENTO_ANATEL'];
				$ogToSave->data_abertura = $og['DT_ABERTURA'];
				$ogToSave->produto = $og['PRODUTO'];
				$ogToSave->servico = $og['SERVICO'];
				$ogToSave->regional = $og['REGIONAL'];
				$ogToSave->localidade = $og['LOCALIDADE'];
				$ogToSave->tecnico = $og['TECNICO'];
				$ogToSave->descricao = $og['DESC_EQPTO'];
				
				// if($og['INTERROMPEU'] == "Y"){
				// 	$ogToSave->interrompeu = "Sim";
				// }elseif($og['INTERROMPEU'] == "N"){
				// 	$ogToSave->interrompeu = "Não";
				// }else{
				// $ogToSave->interrompeu = "Não informado";
				// }
				
				// $ogToSave->qtd_clientes = $og['QNT_CLIENTE'];
				// $ogToSave->obs = $og['OBS'];
				$ogToSave->save();
				error_log("[NEW] - Protocolo " . Og::where('protocolo',  $og['PROTOCOLO'])->first()['protocolo'] . " salvo com sucesso!");
			}
		}
		$this->closeSavedOgs();
	}
	

    /**
     * Display the specified resource.
     *
     * @param  \App\Og  $og
     * @return \Illuminate\Http\Response
     */
    public function show(Og $og)
    {
		// there's no specific view for a single Pf
	}    
	

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Og  $og
     * @return \Illuminate\Http\Response
     */
    public function edit(Og $og)
    {
        // there's no editing of OGs here
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Og  $og
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Og $og)
    {
        // we don't update saved OGs, they're static
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Og  $og
     * @return \Illuminate\Http\Response
     */
    public function destroy(Og $og)
    {
        // we don't plan do delete save OGs, they're meant to be a log
    }
	
	public function showOpenOgs()
    {
        $ogs =  Og::orderBy('protocolo', 'desc');
		foreach($ogs as $i=>$og){
			if($og['status'] == "FECHADO"){
				$ogs->forget($i);
			}
		}
		return view('ogs.open')->with('ogs', $ogs);
	}

	public function showClosedOgs()
    {
        $ogs =  Og::orderBy('protocolo', 'desc')->paginate(15);
		foreach($ogs as $i=>$og){
			if($og['status'] == "ABERTO"){
				$ogs->forget($i);
			}
		}
		return view('ogs.closed')->with('ogs', $ogs);
	}
    
    public function showLiveJson()
    {
		$ogs = $this->getOgsFromUrl();
		//dd($ogs);
		$ogs = collect($ogs)->sortBy('DT_ABERTURA')->reverse()->toArray();
		return view('ogs.index')->with('ogs', $ogs);
    }
	
	public function getOgsFromUrl()
    {
        $url = 'http://portaldesempenho.algartelecom.com.br/api/filas?email=rodrigosv@algartelecom.com.br&password=bXVkYXIxMjM=&id=8';
		$ogs = json_decode(file_get_contents($url), true);
		$ogs = $ogs['result'];
		return $ogs;
		print $url;
    }
	
	public function closeSavedOgs()
	{
		$liveOgs = $this->getOgsFromUrl();
		$savedOgs = Og::pluck('protocolo')->toArray();
		foreach($savedOgs as $saved){
			if(array_search($saved, array_column($liveOgs, 'PROTOCOLO'))){
				error_log("[ABERTO] O chamado: " . Og::where('protocolo',  $saved)->first()['protocolo'] . " ainda não foi encerrado. " . "Status atual: " .Og::where('protocolo',  $saved)->first()['status']);
			}elseif (Og::where('protocolo',  $saved)->first()['status'] == "FECHADO"){
				error_log("[VERIFICADO] Chamado " . Og::where('protocolo',  $saved)->first()['protocolo'] . " já está encerrado.");
			}else{
				error_log("[ENCERRADO] Chamado " . Og::where('protocolo',  $saved)->first()['protocolo'] . " não foi localizado nas OGS ativas. Será encerrado.");
				Og::where('protocolo',  $saved)->update(['status' => "FECHADO"]);
				error_log("[UPDATE] Novo status: " .Og::where('protocolo',  $saved)->first()['status']);
			}		
		}
	}
	public function findOg(Request $request)
	{

		if (!$request) {
			$ogs = Og::all();
		} else {
			$ogs = Og::where('protocolo', 'LIKE', $request)
				->paginate(10);
		}
		
		return view('ogs.list')->with('ogs', $ogs);
	}
	
	public function search(Request $request)
	{
		// $protocolo = $request->input('protocolo');

		//now get all user and services in one go without looping using eager loading
		//In your foreach() loop, if you have 1000 users you will make 1000 queries

		// $ogs = Og::with('protocolo', 
		// 	function($query) use ($protocolo) {
		// 		$query->where('protocolo', 'LIKE', '%' . $protocolo . '%');
		// 	})->get();
		// print $ogs;

		$query = Request::input('search');

		$ogs = DB::table('ogs')->where('protocolo', 'LIKE', '%' . $query . '%')->paginate(10);


		Log::debug('ENTROU NA FUNCAO SEARCH');

		return view('ogs.closed', compact('ogs', $ogs));
	}
	
}

resources/views/portal/events.blade.php
@extends('adminlte::page')

@section('title', 'Portal Corporativo - Plantão')

@section('content_header')
		
<div class="container">
			
			<div class="painel-heading">Cadastrar Plantonista</div>
			
			<div class="painel-body">
			
			{!! Form::open(array('route' => 'events.add','method'=>'POST','files'=>'true')) !!}
				<div class="row">
					<div class="col-xs-12 col-sm-12 col-md-12">
						@if (Session::has('success'))
							<div class="alert alert-success">{{Session::get('success') }}</div>
						@elseif (Session::has('warnning'))
							<div class="alert alert-danger">{{Session::get('warnning') }}</div>
						@endif
					</div>
						<div class="col-xs-4 col-sm-4 col-md-4">
							<div class="form-group">
								{!! Form::label('envet_name','Plantonista:') !!}
								<div class=''>
								{!! Form::text('event_name', null, ['class' => 'form-control']) !!}
								{!! $errors->first('event_name', '<p class="alert alert-danger">:message</p>') !!}
								</div>
							</div>
						</div>	
						
						<div class="col-xs-3 col-sm-3 col-md-3">
							<div class="form-group">
								{!! Form::label('start_date','Inicio:') !!}
								<div class=''>
								{!! Form::date('start_date', null, ['class' => 'form-control']) !!}
								{!! $errors->first('start_date', '<p class="alert alert-danger">:message</p>') !!}
								</div>
							</div>
						</div>	

						<div class="col-xs-3 col-sm-3 col-md-3">
							<div class="form-group">
								{!! Form::label('end_date','Fim:') !!}
								<div class=''>
								{!! Form::date('end_date', null, ['class' => 'form-control']) !!}
								{!! $errors->first('end_date', '<p class="alert alert-danger">:message</p>') !!}
								</div>
							</div>
						</div>	

						<div class="col-xs-1 col-sm-1 col-md-1 text-center"> &nbsp;<br/>
						{!! Form::submit('Add Event',['class'=>'btn btn-primary']) !!}
						</div>
					</div>
					{!! Form::close() !!}
					</div>
					
					</div>
	
	
					<div class="panel panel-primary">
					<div class="panel-heading">Calendário</div>
					<div class="panel-body" >
                  {!! $calendar_details->calendar() !!}
						
			</div>
			</div>
			</div>
@endsection
@section('adminlte_js')
	<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.2.7/fullcalendar.min.js"></script>
{!! $calendar_details->script() !!}
@stop

resources/views/portal/faq.blade.php
@extends('adminlte::page')

@section('title', 'Portal Corporativo - Faq')

@section('content_header')
<h1>Faq's</h1>
<ol class="breadcrumb">
    <li><a href="{{route('home')}}"><i class="fa fa-home"></i> Home</a></li>
    <li class="active">Faq's</li>
    <li><button class="btn btn-primary btn-xs" type="button" data-toggle="modal" data-target="#modalfaq"><i class="fa fa-plus fa-fw"></i> Add Pergunta</button></li>
</ol>
@stop

@section('content')
  <div class="row">
      <div class="col-lg-12">
            @include('includes.alerts')
        @forelse ($faqs as $faq)
            <div class="faq-item">
                <div class="row">
                    <div class="col-md-9">
                    <a data-toggle="collapse" href="#faq{{$faq->id}}" class="faq-question collapsed" aria-expanded="false">{{$faq->pergunta}}</a>
                    <small>Adicionado por 
                    <strong title="{{$faq->user->name}}">
                            {{$faq->user->username}}
                        </strong> 
                    <i class="fa fa-clock-o fa-fw"></i> {{$faq->created_at}}</small>
                    </div>
                    <div class="col-md-3 text-right">
                        <span class="small font-bold">Tag</span>
                        <div class="tag-list">
                            @foreach ($faq->tag as $tag)
                            <span class="tag-item">{{$tag->tag}}</span>
                            @endforeach
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div id="faq{{$faq->id}}" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                            @if ($faq->resposta)
                        <div class="faq-answer" id="respondeu-{{$faq->id}}">
                                    <p>
                                        {!!$faq->resposta->resposta!!}
                                    </p>
                                </div>
                            @else
                            <div class="callout callout-info" id="info-{{$faq->id}}">
                            <p>Nenhuma resposta cadastrada! <button type="button" class="btn btn-success btn-xs" onclick="$('#responder-{{$faq->id}}').show(); $('#info-{{$faq->id}}').hide()"><i class="fa fa-pencil fa-fw"></i> Responder</button></p>
                                </div>
                            @endif
                            <div class="faq-answer" style="display: none" id="responder-{{$faq->id}}">
                                    <form action="{{route('faq.create')}}" method="get">
                                    <input type="hidden" name="faq_id" value="{{$faq->id}}">
                                            <div class="form-group">
                                            <label for="resposta">Resposta</label>
                                                <textarea class="form-control" name="resposta" id="resposta" rows="3">@if ($faq->resposta) {!!$faq->resposta->resposta!!} @endif</textarea>
                                            </div>
                                            <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-save fa-fw"></i> Salvar</button>
                                    </form>
                                </div>
                            <p class="text-right m-t-sm">
                                    @can('edit_faq')
                                        <button type="button" {{$faq->resposta ? '' : 'disabled'}} onclick="$('#responder-{{$faq->id}}').show(); $('#respondeu-{{$faq->id}}').hide()" class="btn btn-primary btn-xs"><i class="fa fa-edit fa-fw"></i> Editar</button>
                                    @endcan
                                    @can('delete_faq')
                            <button type="button" onclick="apagar({{$faq->id}})" class="btn btn-danger btn-xs"><i class="fa fa-trash fa-fw"></i> Apagar</button>
                                    @endcan
                                </p>
                        </div>
                    </div>
                </div>
            </div>
        <form id="delete-faq-{{$faq->id}}" action="{{ route('faq.destroy', $faq->id) }}" method="POST" style="display: none;">
                    @method('DELETE')
                    @csrf
            </form>
        @empty
        <div class="callout callout-info">
                <p>Nenhuma pergunta cadastrada!</p>
              </div>
        @endforelse
        <p class="text-right">{{ $faqs->links() }}</p>
    </div>
  </div>
  <div class="modal fade" id="modalfaq" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
          <form action="" method="POST">
                @csrf
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title">Adicionar Pergunta</h4>
            </div>
            <div class="modal-body">
                    <div class="form-group">
                      <label for="pergunta">Pergunta</label>
                    <input type="text" name="pergunta" id="pergunta" class="form-control" autocomplete="off" placeholder="Pergunta" aria-describedby="helpId" value="{{old('pergunta')}}">
                    </div>
                    <div class="form-group">
                      <label for="tag">Tag</label>
                      <select name="tag[]" id="tag" class="form-control select2" multiple="multiple"  style="width: 100%;">
                      </select>
                      <small class="text-muted">*Utilize espaço( ), virgula(,) ou ponto(.) para inserir a tag.</small>
                    </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary"><i class="fa fa-send fa-fw"></i> Enviar</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-times fa-fw"></i> Fechar</button>
            </div>
        </form>
          </div>
        </div>
      </div>
      <div class="modal fade" id="modalresposta" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
              <form action="{{route('faq.create')}}" method="GET">
                    @csrf
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title">Responder</h4>
                </div>
                <div class="modal-body">
                        <div class="form-group">
                          <label for="resposta">Resposta</label>
                          <textarea class="form-control" name="resposta" id="resposta" rows="3">{{old('resposta')}}</textarea>
                        </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary"><i class="fa fa-send fa-fw"></i> Enviar</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-times fa-fw"></i> Fechar</button>
                </div>
            </form>
              </div>
            </div>
          </div>
          <div class="modal fade" id="modaledit" tabindex="-1" role="dialog">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                  <form action="" method="POST">
                        @csrf
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <h4 class="modal-title">Responder</h4>
                    </div>
                    <div class="modal-body">
                            <div class="form-group">
                              <label for="resposta">Resposta</label>
                              <textarea class="form-control" name="resposta" id="resposta" rows="3">{{old('resposta')}}</textarea>
                            </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary"><i class="fa fa-send fa-fw"></i> Enviar</button>
                        <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-times fa-fw"></i> Fechar</button>
                    </div>
                </form>
                  </div>
                </div>
              </div>
@stop
@push('js')
<script>
$(function () {
    $('select').select2({
        language: "pt-BR",
        tags : true,
        tokenSeparators: [',', ' ', '.']
    });
});

function apagar(id){

    var r = confirm("ATENÇÃO! Deseja apagar a pergunta selecionada?");
    if (r == true) {
        document.getElementById('delete-faq-'+id).submit();
    } else {
        return false;
    }
}
</script>
@endpush

resources/views/portal/home.blade.php
@extends('adminlte::page')

@section('title', 'Portal Corporativo')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')
    <p>You are logged in!</p>
@stop

resources/views/portal/tel.blade.php
@extends('adminlte::page')

@section('title', 'Portal Corporativo - Forúm')

@section('content_header')

<h1>Telefones Utéis</h1>
<ol class="breadcrumb">
    <li><a href="{{route('home')}}"><i class="fa fa-home"></i> Home</a></li>
    <li class="active">Telefones Utéis</li>
    <!--<li><button class="btn btn-primary btn-xs" type="button" data-toggle="modal" data-target="#modalfaq"><i class="fa fa-plus fa-fw"></i> Add Contato</button></li>-->
</ol>
@stop

@section('content')
<table class="table table-striped">
	<tr>
		<th>Nome</th>
		<th>Telefone</th>
        <th>Email</th>
	</tr>
	@foreach ($tels as $tel)
	<tr>
		<td>{{$tel->name}}</td>
		<td>{{$tel->tel}}</td>
        <td>{{$tel->email}}</td>
	</tr>
	@endforeach
</table>

@stop